apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: {{.Values.replicas}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wordpress-pvc
          persistentVolumeClaim:
            claimName: wordpress-pvc
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
          - name: WORDPRESS_DB_USER
            value: {{.Values.wordpress_user}}
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-wp
                key: wordpress_db_password
          - name: WORDPRESS_DB_NAME
            value: {{.Values.wordpress_db_name}}
          - name: WORDPRESS_DB_HOST
            value: {{.Values.wordpress_db_host}}
        ports:
          - name: wordpress-web
            protocol: TCP
            containerPort: 80
        volumeMounts:
          - name: wordpress-pvc
            mountPath: /var/www/html
