apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: {{.Values.namespace}}
type: Opaque
data:
  mariadb_password: {{.Values.secrets.mariadb_password}}
  mariadb_root_password: {{.Values.secrets.mariadb_root_password}}