apiVersion: v1
kind: Service
metadata:
  name: mariadb-api
  namespace: {{.Values.namespace}}
  labels:
    app: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - name: mariadb-api
    port: 3306
    protocol: TCP