apiVersion: v1
kind: Service
metadata:
  name: wordpress-web
  namespace: {{.Values.namespace}}
  labels:
    app: wordpress
spec:
  ports:
    - port: {{.Values.http_port}}
  selector:
    app: wordpress
  type: NodePort